In [13]:
import pandas as pd
import numpy as np
import geopandas as gpd
from glob import glob

import matplotlib.pyplot as plt

from shapely.geometry import Point

In [65]:
paths = sorted(glob("/data/nature_run/fulldays_reduced/cpl_merged/*.pkl"))
print(paths)

['/data/nature_run/fulldays_reduced/cpl_merged/cpl_all_20060315.pkl', '/data/nature_run/fulldays_reduced/cpl_merged/cpl_all_20060515.pkl', '/data/nature_run/fulldays_reduced/cpl_merged/cpl_all_20060615.pkl', '/data/nature_run/fulldays_reduced/cpl_merged/cpl_all_20060715.pkl', '/data/nature_run/fulldays_reduced/cpl_merged/cpl_all_20060803.pkl', '/data/nature_run/fulldays_reduced/cpl_merged/cpl_all_20060815.pkl', '/data/nature_run/fulldays_reduced/cpl_merged/cpl_all_20060915.pkl', '/data/nature_run/fulldays_reduced/cpl_merged/cpl_all_20061015.pkl', '/data/nature_run/fulldays_reduced/cpl_merged/cpl_all_20061115.pkl', '/data/nature_run/fulldays_reduced/cpl_merged/cpl_all_20061215.pkl']

In [7]:
df = pd.read_pickle(paths[0])
df.head()
df.geometry

0          POINT (-179.93800 -45.00000)
1          POINT (-179.87500 -45.00000)
2          POINT (-179.81200 -45.00000)
3          POINT (-179.75000 -45.00000)
4          POINT (-179.68800 -45.00000)
                       ...
1099865       POINT (122.00000 5.12500)
1099866       POINT (122.00000 5.18800)
1099867       POINT (122.00000 5.25000)
1099868       POINT (122.00000 5.31200)
1099869       POINT (122.00000 5.37500)
Name: geometry, Length: 1099870, dtype: geometry

In [8]:
df.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [10]:
npz_paths = sorted(glob("/data/nature_run/fulldays_reduced/*.npz"))
print(npz_paths)

['/data/nature_run/fulldays_reduced/all_20060315.npz', '/data/nature_run/fulldays_reduced/all_20060515.npz', '/data/nature_run/fulldays_reduced/all_20060615.npz', '/data/nature_run/fulldays_reduced/all_20060715.npz', '/data/nature_run/fulldays_reduced/all_20060803.npz', '/data/nature_run/fulldays_reduced/all_20060815.npz', '/data/nature_run/fulldays_reduced/all_20060915.npz', '/data/nature_run/fulldays_reduced/all_20061015.npz', '/data/nature_run/fulldays_reduced/all_20061115.npz', '/data/nature_run/fulldays_reduced/all_20061215.npz']

In [12]:
data = np.load(npz_paths[0])
print(list(data.keys()))
mh_data = data['scalar']
print(mh_data)

['hsel', 'mh', 'scalar', 'table']
[[-4.50000000e+01 -1.80000000e+02  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  2.00603150e+11]
 [-4.50000000e+01 -1.79938000e+02  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  2.00603150e+11]
 [-4.50000000e+01 -1.79875000e+02  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  2.00603150e+11]
 ...
 [ 3.86250000e+01  1.78750000e+02  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  2.00603152e+11]
 [ 3.86250000e+01  1.78812000e+02  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  2.00603152e+11]
 [ 3.86880000e+01  1.78625000e+02  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  2.00603152e+11]]

In [50]:


print(mh_times[:100])

['0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000', '0000']

In [64]:
geometry = [Point(lon, lat) for lon, lat in zip(mh_data[:,1], mh_data[:,0])]
mh_times = mh_data[:,-1].astype(int).astype(str)
mh_times = [x[-4:] for x in mh_times]

gdf = gpd.GeoDataFrame(geometry=geometry)

gdf['times_npz'] = mh_times
gdf['index_npz'] = list(range(len(mh_times)))
gdf.set_crs(epsg=4326, inplace=True)
gdf.tail()

                           geometry times_npz  index_npz
5522303  POINT (178.62500 38.62500)      2100    5522303
5522304  POINT (178.68800 38.62500)      2100    5522304
5522305  POINT (178.75000 38.62500)      2100    5522305
5522306  POINT (178.81200 38.62500)      2100    5522306
5522307  POINT (178.62500 38.68800)      2100    5522307

In [66]:
times_all = set(mh_times)
times_all_2 = set(df['time'])
print(times_all)
print(times_all_2)
for i in times_all_2:
    print(i)

{'0600', '2100', '1500', '0000', '1800', '1200', '0300', '0900'}
{'0600', '2100', '1500', '0000', '1800', '1200', '0300', '0900'}
0600
2100
1500
0000
1800
1200
0300
0900

In [53]:
df.head()

,cpl_0,cpl_1,cpl_2,cpl_3,cpl_4,cpl_5,cpl_6,cpl_7,cpl_8,cpl_9,...,cpl_726,cpl_727,cpl_728,cpl_729,cpl_730,cpl_731,cpl_732,cpl_733,geometry,time
0,-0.0,3.851809e-07,4.037199e-07,4.159510e-07,4.301965e-07,4.153502e-07,4.711740e-07,4.641689e-07,4.493346e-07,5.396949e-07,...,0.000021,0.000040,-0.000121,-0.000150,0.000012,0.000146,-0.000333,-0.000122,POINT (-179.93800 -45.00000),0000
1,-0.0,3.836414e-07,4.012846e-07,4.330225e-07,4.250369e-07,4.202643e-07,4.672969e-07,4.571378e-07,4.733692e-07,5.034269e-07,...,-0.000111,-0.000177,-0.000007,-0.000074,0.000117,0.000079,-0.000084,-0.000228,POINT (-179.87500 -45.00000),0000
2,-0.0,3.851445e-07,4.043617e-07,4.083747e-07,4.221684e-07,4.283106e-07,4.260496e-07,4.694006e-07,5.122949e-07,4.715084e-07,...,0.000191,0.000069,0.000002,0.000174,0.000021,0.000060,0.000156,0.000300,POINT (-179.81200 -45.00000),0000
3,-0.0,3.813320e-07,4.040026e-07,4.172313e-07,4.384864e-07,4.596241e-07,4.769400e-07,4.781560e-07,5.386214e-07,5.381712e-07,...,-0.000073,-0.000197,0.000249,0.000012,0.000174,-0.000017,-0.000084,0.000041,POINT (-179.75000 -45.00000),0000
4,-0.0,3.847323e-07,4.103014e-07,4.122353e-07,4.275999e-07,4.667760e-07,4.730636e-07,4.307845e-07,5.168392e-07,4.671118e-07,...,0.000134,-0.000055,0.000030,-0.000150,-0.000265,-0.000017,-0.000238,-0.000017,POINT (-179.68800 -45.00000),0000

In [58]:
gdf_all = gdf.to_crs(epsg=6933)
gdf_cpl = df.to_crs(epsg=6933)

In [59]:
gdf_all.head()

                             geometry times_npz
0  POINT (-17367530.445 -5180102.329)      0000
1  POINT (-17361548.296 -5180102.329)      0000
2  POINT (-17355469.660 -5180102.329)      0000
3  POINT (-17349391.024 -5180102.329)      0000
4  POINT (-17343408.875 -5180102.329)      0000

In [60]:
gdf_cpl.head()

,cpl_0,cpl_1,cpl_2,cpl_3,cpl_4,cpl_5,cpl_6,cpl_7,cpl_8,cpl_9,...,cpl_726,cpl_727,cpl_728,cpl_729,cpl_730,cpl_731,cpl_732,cpl_733,geometry,time
0,-0.0,3.851809e-07,4.037199e-07,4.159510e-07,4.301965e-07,4.153502e-07,4.711740e-07,4.641689e-07,4.493346e-07,5.396949e-07,...,0.000021,0.000040,-0.000121,-0.000150,0.000012,0.000146,-0.000333,-0.000122,POINT (-17361548.637 -5180102.329),0000
1,-0.0,3.836414e-07,4.012846e-07,4.330225e-07,4.250369e-07,4.202643e-07,4.672969e-07,4.571378e-07,4.733692e-07,5.034269e-07,...,-0.000111,-0.000177,-0.000007,-0.000074,0.000117,0.000079,-0.000084,-0.000228,POINT (-17355469.660 -5180102.329),0000
2,-0.0,3.851445e-07,4.043617e-07,4.083747e-07,4.221684e-07,4.283106e-07,4.260496e-07,4.694006e-07,5.122949e-07,4.715084e-07,...,0.000191,0.000069,0.000002,0.000174,0.000021,0.000060,0.000156,0.000300,POINT (-17349390.683 -5180102.329),0000
3,-0.0,3.813320e-07,4.040026e-07,4.172313e-07,4.384864e-07,4.596241e-07,4.769400e-07,4.781560e-07,5.386214e-07,5.381712e-07,...,-0.000073,-0.000197,0.000249,0.000012,0.000174,-0.000017,-0.000084,0.000041,POINT (-17343408.875 -5180102.329),0000
4,-0.0,3.847323e-07,4.103014e-07,4.122353e-07,4.275999e-07,4.667760e-07,4.730636e-07,4.307845e-07,5.168392e-07,4.671118e-07,...,0.000134,-0.000055,0.000030,-0.000150,-0.000265,-0.000017,-0.000238,-0.000017,POINT (-17337427.067 -5180102.329),0000

In [63]:
merged_df = []

for i in set(gdf_cpl["time"]):
    cpl_at_time = gdf_cpl[gdf_cpl['time'] == i]
    npz_at_time = gdf_all[gdf_all['times_npz'] == i]
    cpl_at_time.sjoin_nearest(npz_at_time, how='left', distance_col='distance')
    merged_df.append(cpl_at_time)
merged_df = pd.concat(merged_df, ignore_index=True)
merged_df.head()

,cpl_0,cpl_1,cpl_2,cpl_3,cpl_4,cpl_5,cpl_6,cpl_7,cpl_8,cpl_9,...,cpl_726,cpl_727,cpl_728,cpl_729,cpl_730,cpl_731,cpl_732,cpl_733,geometry,time
0,-0.0,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,...,-0.000001,-0.000001,-0.000001,-0.000001,-0.000001,-0.000001,-0.000001,-0.000001,POINT (1905604.035 -4386768.412),0600
1,-0.0,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,...,0.000008,0.000008,-0.000001,0.000008,-0.000001,-0.000001,-0.000001,-0.000001,POINT (1899621.859 -4380402.876),0600
2,-0.0,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,...,0.000008,-0.000001,-0.000001,-0.000001,-0.000001,-0.000001,-0.000001,0.000008,POINT (1887464.641 -4374032.282),0600
3,-0.0,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,...,-0.000001,-0.000001,-0.000001,0.000008,-0.000001,-0.000001,-0.000001,-0.000001,POINT (1887464.641 -4367553.822),0600
4,-0.0,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,0.000001,...,-0.000001,-0.000001,-0.000001,-0.000001,0.000008,-0.000001,-0.000001,-0.000001,POINT (1887464.641 -4361070.156),0600

In [29]:
gdf_merged = gpd.sjoin_nearest(gdf_cpl, gdf_all, how='left', distance_col='distances')

In [32]:
gdf_merged.head(10)

,cpl_0,cpl_1,cpl_2,cpl_3,cpl_4,cpl_5,cpl_6,cpl_7,cpl_8,cpl_9,...,cpl_729,cpl_730,cpl_731,cpl_732,cpl_733,geometry,time,index_right,i,distances
0,-0.0,3.851809e-07,4.037199e-07,4.159510e-07,4.301965e-07,4.153502e-07,4.711740e-07,4.641689e-07,4.493346e-07,5.396949e-07,...,-0.000150,0.000012,0.000146,-0.000333,-0.000122,POINT (-17361548.637 -5180102.329),0000,4738760,4738760,0.341565
0,-0.0,3.851809e-07,4.037199e-07,4.159510e-07,4.301965e-07,4.153502e-07,4.711740e-07,4.641689e-07,4.493346e-07,5.396949e-07,...,-0.000150,0.000012,0.000146,-0.000333,-0.000122,POINT (-17361548.637 -5180102.329),0000,1,1,0.341565
1,-0.0,3.836414e-07,4.012846e-07,4.330225e-07,4.250369e-07,4.202643e-07,4.672969e-07,4.571378e-07,4.733692e-07,5.034269e-07,...,-0.000074,0.000117,0.000079,-0.000084,-0.000228,POINT (-17355469.660 -5180102.329),0000,4738761,4738761,0.000000
1,-0.0,3.836414e-07,4.012846e-07,4.330225e-07,4.250369e-07,4.202643e-07,4.672969e-07,4.571378e-07,4.733692e-07,5.034269e-07,...,-0.000074,0.000117,0.000079,-0.000084,-0.000228,POINT (-17355469.660 -5180102.329),0000,2,2,0.000000
2,-0.0,3.851445e-07,4.043617e-07,4.083747e-07,4.221684e-07,4.283106e-07,4.260496e-07,4.694006e-07,5.122949e-07,4.715084e-07,...,0.000174,0.000021,0.000060,0.000156,0.000300,POINT (-17349390.683 -5180102.329),0000,4738762,4738762,0.341565
2,-0.0,3.851445e-07,4.043617e-07,4.083747e-07,4.221684e-07,4.283106e-07,4.260496e-07,4.694006e-07,5.122949e-07,4.715084e-07,...,0.000174,0.000021,0.000060,0.000156,0.000300,POINT (-17349390.683 -5180102.329),0000,3,3,0.341565
3,-0.0,3.813320e-07,4.040026e-07,4.172313e-07,4.384864e-07,4.596241e-07,4.769400e-07,4.781560e-07,5.386214e-07,5.381712e-07,...,0.000012,0.000174,-0.000017,-0.000084,0.000041,POINT (-17343408.875 -5180102.329),0000,4738763,4738763,0.000000
3,-0.0,3.813320e-07,4.040026e-07,4.172313e-07,4.384864e-07,4.596241e-07,4.769400e-07,4.781560e-07,5.386214e-07,5.381712e-07,...,0.000012,0.000174,-0.000017,-0.000084,0.000041,POINT (-17343408.875 -5180102.329),0000,4,4,0.000000
4,-0.0,3.847323e-07,4.103014e-07,4.122353e-07,4.275999e-07,4.667760e-07,4.730636e-07,4.307845e-07,5.168392e-07,4.671118e-07,...,-0.000150,-0.000265,-0.000017,-0.000238,-0.000017,POINT (-17337427.067 -5180102.329),0000,4738764,4738764,0.341565
4,-0.0,3.847323e-07,4.103014e-07,4.122353e-07,4.275999e-07,4.667760e-07,4.730636e-07,4.307845e-07,5.168392e-07,4.671118e-07,...,-0.000150,-0.000265,-0.000017,-0.000238,-0.000017,POINT (-17337427.067 -5180102.329),0000,5,5,0.341565

In [33]:
distances = gdf_merged['distances']

In [42]:
print(np.min(distances), np.max(distances), np.average(distances), np.std(distances))
print(np.sum(distances<0.1))

0.0 574866.7542974338 6425.764246109189 26338.021636635272
1146847